//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DEPO()
        {
            this.TBL_STOK_HAREKET_LOG = new HashSet<TBL_STOK_HAREKET_LOG>();
            this.TBL_STOK_HAREKET2 = new HashSet<TBL_STOK_HAREKET2>();
            this.TBL_STOK = new HashSet<TBL_STOK>();
        }
    
        public int DEPO_ID { get; set; }
        public string DEPO_AD { get; set; }
        public int SUBE_KODU { get; set; }
    
        public virtual TBL_SUBE TBL_SUBE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK_HAREKET_LOG> TBL_STOK_HAREKET_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK_HAREKET2> TBL_STOK_HAREKET2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK> TBL_STOK { get; set; }
    }
}
