//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SIPARIS
    {
        public int ID { get; set; }
        public string SIPARIS_NO { get; set; }
        public int TEKLIF_ID { get; set; }
        public int TALEP_ID { get; set; }
        public System.DateTime OLUSTURULMA_TARIH { get; set; }
        public Nullable<System.DateTime> ONAY_TARIH { get; set; }
        public Nullable<System.DateTime> RED_TARIH { get; set; }
        public int OLUSTURAN_ID { get; set; }
        public Nullable<int> ISLEM_YAPAN_ID { get; set; }
        public int SUBE_ID { get; set; }
        public int SIPARIS_DURUM_ID { get; set; }
        public Nullable<System.DateTime> DURUM_GUNCELLEME_TARIH { get; set; }
    
        public virtual TBL_DURUM TBL_DURUM { get; set; }
        public virtual TBL_SUBE TBL_SUBE { get; set; }
        public virtual TBL_TALEP TBL_TALEP { get; set; }
        public virtual TBL_TEKLIF TBL_TEKLIF { get; set; }
    }
}
