//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STOK_HAREKET2
    {
        public int ID { get; set; }
        public string FISNO { get; set; }
        public string STOK_KODU { get; set; }
        public double MIKTAR { get; set; }
        public string GC_KOD { get; set; }
        public System.DateTime TARIH { get; set; }
        public string SIPARIS_NO { get; set; }
        public Nullable<double> ALIS_MALIYET { get; set; }
        public Nullable<int> KULLANICI_ID { get; set; }
        public Nullable<int> DEPO_ID { get; set; }
        public Nullable<int> STOK_GRUP_ID { get; set; }
        public Nullable<System.DateTime> KAYIT_ZAMAN { get; set; }
        public Nullable<int> SUBE_ID { get; set; }
        public Nullable<int> DEPARTMAN_ID { get; set; }
    
        public virtual TBL_DEPARTMAN TBL_DEPARTMAN { get; set; }
        public virtual TBL_DEPO TBL_DEPO { get; set; }
        public virtual TBL_KULLANICI TBL_KULLANICI { get; set; }
        public virtual TBL_STOK TBL_STOK { get; set; }
        public virtual TBL_STOK_GRUP TBL_STOK_GRUP { get; set; }
        public virtual TBL_SUBE TBL_SUBE { get; set; }
    }
}
