//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_STOK()
        {
            this.TBL_STOK_HAREKET_LOG = new HashSet<TBL_STOK_HAREKET_LOG>();
            this.TBL_STOK_HAREKET2 = new HashSet<TBL_STOK_HAREKET2>();
            this.TBL_TALEP = new HashSet<TBL_TALEP>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SUBE_KODU { get; set; }
        public string STOK_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public string OLCU_BR { get; set; }
        public int GRUP_KODU { get; set; }
        public Nullable<double> A_FIYAT { get; set; }
        public Nullable<double> S_FIYAT { get; set; }
        public Nullable<int> KDV_ORAN { get; set; }
        public Nullable<int> DEPO_KODU { get; set; }
    
        public virtual TBL_DEPO TBL_DEPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK_HAREKET_LOG> TBL_STOK_HAREKET_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK_HAREKET2> TBL_STOK_HAREKET2 { get; set; }
        public virtual TBL_STOK_GRUP TBL_STOK_GRUP { get; set; }
        public virtual TBL_SUBE TBL_SUBE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TALEP> TBL_TALEP { get; set; }
    }
}
