//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SUBE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SUBE()
        {
            this.TBL_DEPO = new HashSet<TBL_DEPO>();
            this.TBL_KULLANICI = new HashSet<TBL_KULLANICI>();
            this.TBL_PLAKA_BIRIM = new HashSet<TBL_PLAKA_BIRIM>();
            this.TBL_SIPARIS = new HashSet<TBL_SIPARIS>();
            this.TBL_STOK = new HashSet<TBL_STOK>();
            this.TBL_STOK_HAREKET_LOG = new HashSet<TBL_STOK_HAREKET_LOG>();
            this.TBL_STOK_HAREKET2 = new HashSet<TBL_STOK_HAREKET2>();
            this.TBL_TALEP = new HashSet<TBL_TALEP>();
            this.TBL_TEKLIF = new HashSet<TBL_TEKLIF>();
        }
    
        public int ID { get; set; }
        public string SUBE_ADI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DEPO> TBL_DEPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KULLANICI> TBL_KULLANICI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PLAKA_BIRIM> TBL_PLAKA_BIRIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SIPARIS> TBL_SIPARIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK> TBL_STOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK_HAREKET_LOG> TBL_STOK_HAREKET_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK_HAREKET2> TBL_STOK_HAREKET2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TALEP> TBL_TALEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TEKLIF> TBL_TEKLIF { get; set; }
    }
}
