//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STOK_GRUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_STOK_GRUP()
        {
            this.TBL_STOK = new HashSet<TBL_STOK>();
            this.TBL_STOK_HAREKET_LOG = new HashSet<TBL_STOK_HAREKET_LOG>();
            this.TBL_STOK_HAREKET2 = new HashSet<TBL_STOK_HAREKET2>();
        }
    
        public int ID { get; set; }
        public string GRUP_ADI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK> TBL_STOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK_HAREKET_LOG> TBL_STOK_HAREKET_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK_HAREKET2> TBL_STOK_HAREKET2 { get; set; }
    }
}
