//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEPARTMAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DEPARTMAN()
        {
            this.TBL_PLAKA_BIRIM = new HashSet<TBL_PLAKA_BIRIM>();
            this.TBL_STOK_HAREKET_LOG = new HashSet<TBL_STOK_HAREKET_LOG>();
            this.TBL_STOK_HAREKET2 = new HashSet<TBL_STOK_HAREKET2>();
            this.TBL_TALEP = new HashSet<TBL_TALEP>();
        }
    
        public int ID { get; set; }
        public string DEPARTMAN_AD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PLAKA_BIRIM> TBL_PLAKA_BIRIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK_HAREKET_LOG> TBL_STOK_HAREKET_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STOK_HAREKET2> TBL_STOK_HAREKET2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TALEP> TBL_TALEP { get; set; }
    }
}
