//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PLAKA_BIRIM
    {
        public int ID { get; set; }
        public int SUBE_ID { get; set; }
        public string PLAKA_BIRIM { get; set; }
        public int DEPARTMAN_ID { get; set; }
    
        public virtual TBL_DEPARTMAN TBL_DEPARTMAN { get; set; }
        public virtual TBL_SUBE TBL_SUBE { get; set; }
    }
}
