//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class U_Entities : DbContext
    {
        public U_Entities()
            : base("name=U_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<TBL_DEPARTMAN> TBL_DEPARTMAN { get; set; }
        public virtual DbSet<TBL_DEPO> TBL_DEPO { get; set; }
        public virtual DbSet<TBL_DURUM> TBL_DURUM { get; set; }
        public virtual DbSet<TBL_FIRMA> TBL_FIRMA { get; set; }
        public virtual DbSet<TBL_KULLANICI> TBL_KULLANICI { get; set; }
        public virtual DbSet<TBL_PLAKA_BIRIM> TBL_PLAKA_BIRIM { get; set; }
        public virtual DbSet<TBL_ROL> TBL_ROL { get; set; }
        public virtual DbSet<TBL_SIPARIS> TBL_SIPARIS { get; set; }
        public virtual DbSet<TBL_STOK> TBL_STOK { get; set; }
        public virtual DbSet<TBL_STOK_GRUP> TBL_STOK_GRUP { get; set; }
        public virtual DbSet<TBL_STOK_HAREKET_LOG> TBL_STOK_HAREKET_LOG { get; set; }
        public virtual DbSet<TBL_STOK_HAREKET2> TBL_STOK_HAREKET2 { get; set; }
        public virtual DbSet<TBL_SUBE> TBL_SUBE { get; set; }
        public virtual DbSet<TBL_TALEP> TBL_TALEP { get; set; }
        public virtual DbSet<TBL_TEKLIF> TBL_TEKLIF { get; set; }
        public virtual DbSet<VW_KULLANICI> VW_KULLANICI { get; set; }
        public virtual DbSet<VW_SIPARIS> VW_SIPARIS { get; set; }
        public virtual DbSet<VW_STOK_HAREKET> VW_STOK_HAREKET { get; set; }
        public virtual DbSet<VW_STOK_HAREKET_LOG> VW_STOK_HAREKET_LOG { get; set; }
        public virtual DbSet<VW_TALEP> VW_TALEP { get; set; }
        public virtual DbSet<VW_TEKLIF> VW_TEKLIF { get; set; }
    
        public virtual ObjectResult<IDP_PLAKA_BIRIM_LIST_Result> IDP_PLAKA_BIRIM_LIST(Nullable<int> kULLANICI_ID, Nullable<int> dEPARTMAN_ID)
        {
            var kULLANICI_IDParameter = kULLANICI_ID.HasValue ?
                new ObjectParameter("KULLANICI_ID", kULLANICI_ID) :
                new ObjectParameter("KULLANICI_ID", typeof(int));
    
            var dEPARTMAN_IDParameter = dEPARTMAN_ID.HasValue ?
                new ObjectParameter("DEPARTMAN_ID", dEPARTMAN_ID) :
                new ObjectParameter("DEPARTMAN_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IDP_PLAKA_BIRIM_LIST_Result>("IDP_PLAKA_BIRIM_LIST", kULLANICI_IDParameter, dEPARTMAN_IDParameter);
        }
    
        public virtual ObjectResult<IDP_SIPARIS_GRID_Result> IDP_SIPARIS_GRID(Nullable<int> kULLANICI_ID)
        {
            var kULLANICI_IDParameter = kULLANICI_ID.HasValue ?
                new ObjectParameter("KULLANICI_ID", kULLANICI_ID) :
                new ObjectParameter("KULLANICI_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IDP_SIPARIS_GRID_Result>("IDP_SIPARIS_GRID", kULLANICI_IDParameter);
        }
    
        public virtual int IDP_STOK_HAR_I(string fISNO, string sTOK_KODU, Nullable<double> mIKTAR, string gCKOD, Nullable<System.DateTime> tARIH, Nullable<int> kULLANICI_ID, Nullable<int> dEPARMTAN_ID, string sIPARIS_NO, Nullable<bool> kULLANILDIMI, string pLAKA_BIRIM, string h_NOT)
        {
            var fISNOParameter = fISNO != null ?
                new ObjectParameter("FISNO", fISNO) :
                new ObjectParameter("FISNO", typeof(string));
    
            var sTOK_KODUParameter = sTOK_KODU != null ?
                new ObjectParameter("STOK_KODU", sTOK_KODU) :
                new ObjectParameter("STOK_KODU", typeof(string));
    
            var mIKTARParameter = mIKTAR.HasValue ?
                new ObjectParameter("MIKTAR", mIKTAR) :
                new ObjectParameter("MIKTAR", typeof(double));
    
            var gCKODParameter = gCKOD != null ?
                new ObjectParameter("GCKOD", gCKOD) :
                new ObjectParameter("GCKOD", typeof(string));
    
            var tARIHParameter = tARIH.HasValue ?
                new ObjectParameter("TARIH", tARIH) :
                new ObjectParameter("TARIH", typeof(System.DateTime));
    
            var kULLANICI_IDParameter = kULLANICI_ID.HasValue ?
                new ObjectParameter("KULLANICI_ID", kULLANICI_ID) :
                new ObjectParameter("KULLANICI_ID", typeof(int));
    
            var dEPARMTAN_IDParameter = dEPARMTAN_ID.HasValue ?
                new ObjectParameter("DEPARMTAN_ID", dEPARMTAN_ID) :
                new ObjectParameter("DEPARMTAN_ID", typeof(int));
    
            var sIPARIS_NOParameter = sIPARIS_NO != null ?
                new ObjectParameter("SIPARIS_NO", sIPARIS_NO) :
                new ObjectParameter("SIPARIS_NO", typeof(string));
    
            var kULLANILDIMIParameter = kULLANILDIMI.HasValue ?
                new ObjectParameter("KULLANILDIMI", kULLANILDIMI) :
                new ObjectParameter("KULLANILDIMI", typeof(bool));
    
            var pLAKA_BIRIMParameter = pLAKA_BIRIM != null ?
                new ObjectParameter("PLAKA_BIRIM", pLAKA_BIRIM) :
                new ObjectParameter("PLAKA_BIRIM", typeof(string));
    
            var h_NOTParameter = h_NOT != null ?
                new ObjectParameter("H_NOT", h_NOT) :
                new ObjectParameter("H_NOT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IDP_STOK_HAR_I", fISNOParameter, sTOK_KODUParameter, mIKTARParameter, gCKODParameter, tARIHParameter, kULLANICI_IDParameter, dEPARMTAN_IDParameter, sIPARIS_NOParameter, kULLANILDIMIParameter, pLAKA_BIRIMParameter, h_NOTParameter);
        }
    
        public virtual ObjectResult<IDP_STOK_HAREKET_GRID_Result> IDP_STOK_HAREKET_GRID(Nullable<int> kULLANICI_ID)
        {
            var kULLANICI_IDParameter = kULLANICI_ID.HasValue ?
                new ObjectParameter("KULLANICI_ID", kULLANICI_ID) :
                new ObjectParameter("KULLANICI_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IDP_STOK_HAREKET_GRID_Result>("IDP_STOK_HAREKET_GRID", kULLANICI_IDParameter);
        }
    
        public virtual ObjectResult<IDP_STOK_HAREKET_LOG_GRID_Result> IDP_STOK_HAREKET_LOG_GRID(Nullable<int> kULLANICI_ID)
        {
            var kULLANICI_IDParameter = kULLANICI_ID.HasValue ?
                new ObjectParameter("KULLANICI_ID", kULLANICI_ID) :
                new ObjectParameter("KULLANICI_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IDP_STOK_HAREKET_LOG_GRID_Result>("IDP_STOK_HAREKET_LOG_GRID", kULLANICI_IDParameter);
        }
    
        public virtual ObjectResult<IDP_TALEP_GRID_Result> IDP_TALEP_GRID(Nullable<int> kULLANICI_ID, Nullable<int> dURUM)
        {
            var kULLANICI_IDParameter = kULLANICI_ID.HasValue ?
                new ObjectParameter("KULLANICI_ID", kULLANICI_ID) :
                new ObjectParameter("KULLANICI_ID", typeof(int));
    
            var dURUMParameter = dURUM.HasValue ?
                new ObjectParameter("DURUM", dURUM) :
                new ObjectParameter("DURUM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IDP_TALEP_GRID_Result>("IDP_TALEP_GRID", kULLANICI_IDParameter, dURUMParameter);
        }
    
        public virtual ObjectResult<IDP_TEKLIF_ASAMASINDAKI_TALEPLER_GRID_Result> IDP_TEKLIF_ASAMASINDAKI_TALEPLER_GRID(Nullable<int> kULLANICI_ID)
        {
            var kULLANICI_IDParameter = kULLANICI_ID.HasValue ?
                new ObjectParameter("KULLANICI_ID", kULLANICI_ID) :
                new ObjectParameter("KULLANICI_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IDP_TEKLIF_ASAMASINDAKI_TALEPLER_GRID_Result>("IDP_TEKLIF_ASAMASINDAKI_TALEPLER_GRID", kULLANICI_IDParameter);
        }
    
        public virtual ObjectResult<IDP_TEKLIF_GRID_Result> IDP_TEKLIF_GRID(Nullable<int> kULLANICI_ID, Nullable<int> dURUM, Nullable<int> tALEPID)
        {
            var kULLANICI_IDParameter = kULLANICI_ID.HasValue ?
                new ObjectParameter("KULLANICI_ID", kULLANICI_ID) :
                new ObjectParameter("KULLANICI_ID", typeof(int));
    
            var dURUMParameter = dURUM.HasValue ?
                new ObjectParameter("DURUM", dURUM) :
                new ObjectParameter("DURUM", typeof(int));
    
            var tALEPIDParameter = tALEPID.HasValue ?
                new ObjectParameter("TALEPID", tALEPID) :
                new ObjectParameter("TALEPID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IDP_TEKLIF_GRID_Result>("IDP_TEKLIF_GRID", kULLANICI_IDParameter, dURUMParameter, tALEPIDParameter);
        }
    }
}
