//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_KULLANICI
    {
        public int ID { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string SIFRE { get; set; }
        public string ISIM_SOYISIM { get; set; }
        public string ROL_AD { get; set; }
        public int ROL_ID { get; set; }
        public int SUBE_ID { get; set; }
        public string SUBE_ADI { get; set; }
    }
}
