//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STOK_HAREKET_LOG
    {
        public int ID { get; set; }
        public string STOK_KODU { get; set; }
        public double MIKTAR { get; set; }
        public System.DateTime TARIH { get; set; }
        public int KULLANICI_ID { get; set; }
        public int SUBE_ID { get; set; }
        public bool KULLANILDI_MI { get; set; }
        public int STOK_GRUP_ID { get; set; }
        public int DEPARTMAN_ID { get; set; }
        public int DEPO_ID { get; set; }
        public string PLAKA_BIRIM { get; set; }
        public string H_NOT { get; set; }
        public string DEPARTMAN_AD { get; set; }
        public string DEPO_AD { get; set; }
        public string GRUP_ADI { get; set; }
        public string ISIM_SOYISIM { get; set; }
        public string STOK_ADI { get; set; }
    }
}
