//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SIPARIS
    {
        public int SIPARIS_ID { get; set; }
        public string SIPARIS_NO { get; set; }
        public int TEKLIF_ID { get; set; }
        public int TALEP_ID { get; set; }
        public System.DateTime SIPARIS_OLUSTURULMA_TARIH { get; set; }
        public Nullable<System.DateTime> ONAY_TARIH { get; set; }
        public Nullable<System.DateTime> RED_TARIH { get; set; }
        public string SIPARIS_OLUSTURAN_ISIM { get; set; }
        public string SIPARIS_ISLEM_YAPAN_ISIM { get; set; }
        public int SUBE_ID { get; set; }
        public int SIPARIS_DURUM_ID { get; set; }
        public Nullable<System.DateTime> DURUM_GUNCELLEME_TARIH { get; set; }
        public string TEKLIF_ISLEM_ACIKLAMA { get; set; }
        public decimal TEKLIF_FIYAT { get; set; }
        public string TEKLIF_NOT { get; set; }
        public System.DateTime TEKLIF_OLUSTURULMA_TARIH { get; set; }
        public int TEKLIF_OLUSTURAN_ID { get; set; }
        public string TALEP_ISLEM_ACIKLAMA { get; set; }
        public string DURUM_AD { get; set; }
        public string FIRMA_AD { get; set; }
        public string DEPARTMAN_AD { get; set; }
        public int DEPARTMAN_ID { get; set; }
        public int TALEP_MIKTAR { get; set; }
        public System.DateTime TALEP_OLUSTURULMA_TARIH { get; set; }
        public string PLAKA_BIRIM { get; set; }
        public string TEKLIF_OLUSTURAN_ISIM { get; set; }
        public string TALEP_NO { get; set; }
        public string STOK_ADI { get; set; }
        public string OLCU_BR { get; set; }
        public string GRUP_ADI { get; set; }
        public int STOK_GRUP_ID { get; set; }
        public Nullable<bool> TEKLIF_ONAY1 { get; set; }
        public Nullable<bool> TEKLIF_ONAY2 { get; set; }
        public Nullable<bool> TEKLIF_ONAY3 { get; set; }
        public Nullable<System.DateTime> TEKLIF_ONAY1_TARIH { get; set; }
        public Nullable<System.DateTime> TEKLIF_ONAY2_TARIH { get; set; }
        public Nullable<System.DateTime> TEKLIF_ONAY3_TARIH { get; set; }
        public Nullable<int> TEKLIF_ONAY1_KULLANICI { get; set; }
        public Nullable<int> TEKLIF_ONAY2_KULLANICI { get; set; }
        public Nullable<int> TEKLIF_ONAY3_KULLANICI { get; set; }
        public string TEKLIF_ONAY1_AD { get; set; }
        public string TEKLIF_ONAY2_AD { get; set; }
        public string TEKLIF_ONAY3_AD { get; set; }
        public string TALEP_OLUSTURAN_ISIM { get; set; }
        public Nullable<bool> TALEP_ONAY1 { get; set; }
        public Nullable<bool> TALEP_ONAY2 { get; set; }
        public Nullable<bool> TALEP_ONAY3 { get; set; }
        public Nullable<System.DateTime> TALEP_ONAY1_TARIH { get; set; }
        public Nullable<System.DateTime> TALEP_ONAY2_TARIH { get; set; }
        public Nullable<System.DateTime> TALEP_ONAY3_TARIH { get; set; }
        public Nullable<int> TALEP_ONAY1_KULLANICI { get; set; }
        public Nullable<int> TALEP_ONAY2_KULLANICI { get; set; }
        public Nullable<int> TALEP_ONAY3_KULLANICI { get; set; }
        public string TALEP_ONAY1_AD { get; set; }
        public string TALEP_ONAY2_AD { get; set; }
        public string TALEP_ONAY3_AD { get; set; }
        public string STOK_KODU { get; set; }
        public string DEPO_AD { get; set; }
    }
}
