//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TALEP
    {
        public int ID { get; set; }
        public string TALEP_NO { get; set; }
        public string TALEP_ISLEM_ACIKLAMA { get; set; }
        public int TALEP_MIKTAR { get; set; }
        public int TALEP_DEPARTMAN_ID { get; set; }
        public Nullable<int> TALEP_DURUM_ID { get; set; }
        public string TALEP_NOT { get; set; }
        public System.DateTime OLUSTURULMA_TARIH { get; set; }
        public int OLUSTURAN_ID { get; set; }
        public string DEPARTMAN_AD { get; set; }
        public string DURUM_AD { get; set; }
        public int SUBE_ID { get; set; }
        public string PLAKA_BIRIM { get; set; }
        public string OLUSTURAN_ISIM { get; set; }
        public string STOK_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public string OLCU_BR { get; set; }
        public Nullable<int> GRUP_KODU { get; set; }
        public Nullable<double> A_FIYAT { get; set; }
        public Nullable<double> S_FIYAT { get; set; }
        public Nullable<int> KDV_ORAN { get; set; }
        public Nullable<int> DEPO_KODU { get; set; }
        public Nullable<int> STOK_GRUP_ID { get; set; }
        public string GRUP_ADI { get; set; }
        public Nullable<bool> ONAY1 { get; set; }
        public Nullable<bool> ONAY2 { get; set; }
        public Nullable<bool> ONAY3 { get; set; }
        public Nullable<System.DateTime> ONAY1_TARIH { get; set; }
        public Nullable<System.DateTime> ONAY2_TARIH { get; set; }
        public Nullable<System.DateTime> ONAY3_TARIH { get; set; }
        public Nullable<int> ONAY1_KULLANICI { get; set; }
        public Nullable<int> ONAY2_KULLANICI { get; set; }
        public Nullable<int> ONAY3_KULLANICI { get; set; }
        public string DEPO_AD { get; set; }
        public Nullable<double> ANLIK_STOK_MIKTAR { get; set; }
        public string ONAY1_AD { get; set; }
        public string ONAY2_AD { get; set; }
        public string ONAY3_AD { get; set; }
    }
}
